/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.IrreducibleVertex
-/

import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Algebra.Ring.Int.Defs
import Mathlib.Data.Int.Cast.Basic
import Mathlib.Data.Matrix.Mul
import Mathlib.Tactic.IntervalCases
import PositiveDefiniteTreeLattice.Main.LatticeFoundations.Interfaces
import PositiveDefiniteTreeLattice.Main.RootedCapacity.Interfaces
import PositiveDefiniteTreeLattice.Main.RootedEstimates.Interfaces
